# R environment with .NET 8 for OSPSuite packages
# Uses renv.lock for reproducible package versions
FROM rocker/r-ver:4.4.2

LABEL org.opencontainers.image.source="https://github.com/sorinvoicu/ci"
LABEL org.opencontainers.image.description="Immutable R environment with OSPSuite packages"

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    # Common R package dependencies
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libfontconfig1-dev \
    libfreetype6-dev \
    libpng-dev \
    libjpeg-dev \
    libtiff-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libcairo2-dev \
    libxt-dev \
    libgit2-dev \
    # For clipboard support
    xclip \
    # For .NET
    wget \
    && rm -rf /var/lib/apt/lists/*

# Install .NET 8 SDK
RUN wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh \
    && chmod +x dotnet-install.sh \
    && ./dotnet-install.sh --channel 8.0 --install-dir /usr/share/dotnet \
    && rm dotnet-install.sh \
    && ln -s /usr/share/dotnet/dotnet /usr/local/bin/dotnet

ENV DOTNET_ROOT=/usr/share/dotnet
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1

# Install renv
RUN Rscript -e "install.packages('renv', repos='https://cloud.r-project.org/')"

# Copy renv.lock (generated by CI or committed to repo)
COPY renv.lock /app/renv.lock

# Restore packages from lockfile to system library
# Using renv::restore with library path set to system library
RUN Rscript -e " \
    options(renv.config.pak.enabled = TRUE); \
    renv::restore( \
        lockfile = '/app/renv.lock', \
        library = '/usr/local/lib/R/site-library', \
        prompt = FALSE \
    ) \
"

# Verify key packages load
RUN Rscript -e " \
    packages <- c('rSharp', 'ospsuite', 'tlf', 'ospsuite.utils', 'ospsuite.parameteridentification', 'esqlabsR'); \
    for (pkg in packages) { \
        message('Loading: ', pkg); \
        library(pkg, character.only = TRUE); \
        message(pkg, ' loaded successfully!'); \
    }; \
    message('All packages validated!'); \
"

# Clean up and make library read-only
RUN rm -rf /tmp/* /var/tmp/* \
    && chmod -R a-w /usr/local/lib/R/site-library

# Disable package installation at runtime
RUN echo 'options(install.packages.check.source = "never")' >> /usr/local/lib/R/etc/Rprofile.site \
    && echo 'install.packages <- function(...) stop("Package installation is disabled in this environment")' >> /usr/local/lib/R/etc/Rprofile.site \
    && echo 'remove.packages <- function(...) stop("Package removal is disabled in this environment")' >> /usr/local/lib/R/etc/Rprofile.site \
    && echo 'update.packages <- function(...) stop("Package updates are disabled in this environment")' >> /usr/local/lib/R/etc/Rprofile.site

# Store the lockfile in the image for reference
RUN cp /app/renv.lock /usr/local/lib/R/renv.lock

WORKDIR /workspace

CMD ["R"]
